name: comgora_flutter_web_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^12.1.0
  amplify_flutter: ^1.2.0
  amplify_datastore: ^1.2.0
  amplify_api: ^1.2.0
  amplify_auth_cognito: ^1.2.0
  amplify_storage_s3: ^1.4.0
  google_fonts: ^6.0.0
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/icons/
    - assets/icons/landing_page/

